"""OpenID Connect authentication provider.

``OIDCProvider`` implements the Authorization Code flow for OIDC-compliant
identity providers (e.g., Keycloak, Azure AD, Okta, Google).

Flow summary:

1. **Frontend** calls ``GET /api/auth/oidc/login`` → server returns an
   authorization URL.
2. **Browser** is redirected to the IdP login page.
3. **IdP** redirects back to ``oidc_redirect_uri`` with ``code`` and
   ``state`` query params.
4. **Frontend** sends those to ``POST /api/auth/oidc/callback``.
5. **Server** calls ``handle_callback`` which exchanges the code for tokens,
   fetches the ``userinfo`` endpoint, maps the OIDC claims to a local user,
   and returns a local JWT token pair.

Configuration is stored in the ``configuration`` table under:

- ``oidc_issuer`` — Base issuer URL, e.g. ``https://accounts.google.com``
- ``oidc_client_id`` — OAuth2 client ID
- ``oidc_client_secret`` — OAuth2 client secret
- ``oidc_redirect_uri`` — Callback URI registered with the IdP
- ``oidc_scopes`` — Space-separated scopes (default ``openid profile email``)
- ``oidc_role_claim`` — JWT/userinfo claim containing role(s) (default
  ``roles``)
- ``oidc_role_mapping_json`` — JSON mapping of app roles to claim values,
  e.g. ``{"ADMIN": "app-admin", "APPROVER": "app-approver"}``

The ``authlib`` library is an optional runtime dependency.  All methods
return gracefully when the library is missing or configuration is absent.
"""

import json
from typing import Optional

from sqlalchemy.orm import Session

from ..database.models import Configuration
from .models import User


class OIDCProvider:
    """OpenID Connect authentication provider."""

    def __init__(self, session: Session) -> None:
        """
        Args:
            session: Active SQLAlchemy session used for reading config and
                writing user records.
        """
        self.session = session
        self._config: Optional[dict[str, str]] = None

    # ------------------------------------------------------------------
    # Configuration
    # ------------------------------------------------------------------

    @property
    def config(self) -> dict[str, str]:
        """Lazily load OIDC configuration from the ``configuration`` table."""
        if self._config is None:
            self._config = {}
            keys = (
                "oidc_issuer",
                "oidc_client_id",
                "oidc_client_secret",
                "oidc_redirect_uri",
                "oidc_scopes",
                "oidc_role_claim",
                "oidc_role_mapping_json",
            )
            for key in keys:
                cfg = (
                    self.session.query(Configuration)
                    .filter(Configuration.key == key)
                    .first()
                )
                self._config[key] = cfg.value if cfg else ""
        return self._config

    @property
    def is_configured(self) -> bool:
        """Return ``True`` when both ``oidc_issuer`` and ``oidc_client_id`` are set."""
        return bool(
            self.config.get("oidc_issuer") and self.config.get("oidc_client_id")
        )

    # ------------------------------------------------------------------
    # Authorization URL
    # ------------------------------------------------------------------

    def get_authorization_url(self, state: str) -> Optional[str]:
        """Build the OIDC authorization URL for redirecting the browser.

        Discovers the authorization endpoint from the IdP's
        ``/.well-known/openid-configuration`` document and constructs a
        signed authorization URL embedding the supplied *state* parameter
        (used to prevent CSRF).

        Args:
            state: An opaque random value generated by the caller.  Must be
                verified when processing the callback.

        Returns:
            The full authorization URL string, or ``None`` when the provider
            is not configured or the discovery request fails.
        """
        if not self.is_configured:
            return None

        try:
            import requests as http_requests
            from authlib.integrations.requests_client import OAuth2Session  # type: ignore[import-untyped]

            client = OAuth2Session(
                client_id=self.config["oidc_client_id"],
                client_secret=self.config.get("oidc_client_secret") or None,
                scope=self.config.get("oidc_scopes") or "openid profile email",
                redirect_uri=self.config.get("oidc_redirect_uri") or "",
            )

            discovery_url = (
                f"{self.config['oidc_issuer'].rstrip('/')}/"
                ".well-known/openid-configuration"
            )
            discovery = http_requests.get(discovery_url, timeout=10).json()
            authorization_endpoint: str = discovery["authorization_endpoint"]

            uri, _ = client.create_authorization_url(
                authorization_endpoint, state=state
            )
            return uri

        except Exception:
            return None

    # ------------------------------------------------------------------
    # Callback handling
    # ------------------------------------------------------------------

    def handle_callback(self, code: str, state: str) -> Optional[User]:
        """Exchange an authorization code for tokens and upsert the local user.

        Steps:

        1. Discover token and userinfo endpoints from the IdP metadata.
        2. Exchange *code* for an access token (and optionally ID token).
        3. Fetch the ``userinfo`` endpoint to get claims.
        4. Map claims to a local ``User`` (create or update).

        Args:
            code: The authorization code received from the IdP callback.
            state: The state parameter returned by the IdP (caller is
                responsible for verifying it matches the value from
                ``get_authorization_url``).

        Returns:
            The local ``User`` instance on success, ``None`` on any failure.
        """
        if not self.is_configured:
            return None

        try:
            import requests as http_requests
            from authlib.integrations.requests_client import OAuth2Session  # type: ignore[import-untyped]

            # Discover endpoints.
            discovery_url = (
                f"{self.config['oidc_issuer'].rstrip('/')}/"
                ".well-known/openid-configuration"
            )
            discovery = http_requests.get(discovery_url, timeout=10).json()

            client = OAuth2Session(
                client_id=self.config["oidc_client_id"],
                client_secret=self.config.get("oidc_client_secret") or None,
                redirect_uri=self.config.get("oidc_redirect_uri") or "",
            )

            # Exchange code for token.
            client.fetch_token(discovery["token_endpoint"], code=code)

            # Fetch user claims.
            userinfo: dict[str, object] = client.get(
                discovery["userinfo_endpoint"]
            ).json()

            username: Optional[str] = (
                str(userinfo.get("preferred_username"))
                if userinfo.get("preferred_username")
                else str(userinfo.get("sub", ""))
            )
            if not username:
                return None

            email: Optional[str] = (
                str(userinfo["email"]) if userinfo.get("email") else None
            )
            display_name: str = (
                str(userinfo.get("name")) if userinfo.get("name") else username
            )
            subject: Optional[str] = (
                str(userinfo["sub"]) if userinfo.get("sub") else None
            )
            role = self._map_role(userinfo)

            # Upsert local user.
            local_user = (
                self.session.query(User)
                .filter(User.username == username)
                .first()
            )
            if local_user:
                local_user.display_name = display_name
                local_user.email = email
                local_user.external_id = subject
                local_user.role = role
                local_user.is_active = True
            else:
                local_user = User(
                    username=username,
                    display_name=display_name,
                    email=email,
                    auth_provider="oidc",
                    external_id=subject,
                    role=role,
                    is_active=True,
                )
                self.session.add(local_user)

            self.session.commit()
            self.session.refresh(local_user)
            return local_user

        except ImportError:
            return None
        except Exception:
            return None

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _map_role(self, userinfo: dict[str, object]) -> str:
        """Map OIDC claim values to the highest matching application role.

        Reads the claim named by ``oidc_role_claim`` (default ``roles``)
        from *userinfo* and compares its value(s) against the
        ``oidc_role_mapping_json`` configuration::

            {
                "ADMIN":     "app-admin",
                "APPROVER":  "app-approver",
                "ESTIMATOR": "app-estimator"
            }

        The claim value may be a single string or a list of strings.

        Args:
            userinfo: The decoded userinfo JSON payload from the IdP.

        Returns:
            The highest-privilege role that matches, defaulting to
            ``"VIEWER"`` when no mapping matches.
        """
        role_claim = self.config.get("oidc_role_claim") or "roles"
        raw_roles = userinfo.get(role_claim, [])
        if isinstance(raw_roles, str):
            roles_in_token: list[str] = [raw_roles]
        elif isinstance(raw_roles, list):
            roles_in_token = [str(r) for r in raw_roles]
        else:
            roles_in_token = []

        mapping_str = self.config.get("oidc_role_mapping_json", "{}")
        try:
            mapping: dict[str, str] = json.loads(mapping_str) if mapping_str else {}
        except (json.JSONDecodeError, TypeError):
            mapping = {}

        for role in ("ADMIN", "APPROVER", "ESTIMATOR", "VIEWER"):
            mapped_value = mapping.get(role)
            if mapped_value and mapped_value in roles_in_token:
                return role

        return "VIEWER"
